name: 'Update Static Data In Azure Table Storage'
description: 'A Github action that includes data in a azure table storage from a csv file'
branding:
  icon: upload
  color: blue
inputs:
  connection_string:
    description: "The connection string for the storage account."
    required: true
  csv_file_paths:
    description: "The csv file paths for import."
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-c'
  - ${{ inputs.connection_string }}
  - '-p'
  - ${{ inputs.csv_file_paths }}