name: Upload To Azure Table Storage
on:
  workflow_call:
    inputs:
      tableName:
        required: true
        type: string
      fileName:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      tableName:
        required: true
        description: Table Name
      fileName:
        required: true
        description: File Name

env:
  WORKING_DIR: ./UpdateStaticDataInAzureTableStorage
  TABLE_NAME: ${{ github.event.inputs.tableName || inputs.tableName }}
  FILE_NAME: ${{ github.event.inputs.fileName || inputs.fileName }}
  
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tiagoalmeidadarosa/update-static-data-in-azure-table-storage@v1.0.5
        with:
          table_name: ${{ env.TABLE_NAME }}
          connection_string: ${{ secrets.AzureStorageConnectionString }}
          csv_file_path: ${{ env.WORKING_DIR }}/${{ env.FILE_NAME }}.csv
